define(
   ({
    "instruction": "Lägg till och konfigurera geokodningstjänster eller geoobjektslager som sökkällor. Dessa angivna källor avgör vad som går att söka i sökrutan.",
    "add": "Lägg till sökkälla",
    "addGeocoder": "Lägg till geokodare",
    "geocoder": "Geokodare",
    "setLayerSource": "Ange lagerkälla",
    "setGeocoderURL": "Ange URL till geokodare",
    "searchableLayer": "geoobjektslager",
    "name": "Namn",
    "countryCode": "Landskoder",
    "countryCodeEg": "till exempel ",
    "countryCodeHint": "Om du lämnar det här värdet tomt söks alla länder",
    "locatorUrl": "Geokodarens URL",
    "locatorName": "Geokodarens namn",
    "locatorExample": "Exempel",
    "locatorWarning": "Den här versionen av geokodningstjänsten stöds inte. Widgeten har stöd för geokodningstjänsten 00.0 och högre.",
    "locatorTips": "Förslag finns inte tillgängliga eftersom geokodningstjänsten inte har stöd för förslagsfunktionen.",
    "layerSource": "Lagerkälla",
    "searchLayerTips": "Förslag finns inte tillgängliga eftersom geoobjektstjänsten inte har stöd för pagineringsfunktionen.",
    "placeholder": "Platshållartext",
    "searchFields": "Sökfält",
    "displayField": "Visa fält",
    "exactMatch": "Exakt matchning",
    "maxResults": "Maximala resultat",
    "setSearchFields": "Ange sökfält",
    "set": "Ange",
    "fieldSearchable": "sökbar",
    "fieldName": "Namn",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Avbryt",
    "invalidUrlTip": "Den URL du har angett är ogiltig eller går inte att komma åt."
  })
);