define(
   ({
    "instruction": "Dodaj i skonfiguruj usługi geokodowania lub warstwy obiektów jako źródła wyszukiwania. Źródła te określają, co można wyszukiwać w polu wyszukiwania.",
    "add": "Dodaj źródło wyszukiwania",
    "addGeocoder": "Dodaj geokoder",
    "geocoder": "Geokoder",
    "setLayerSource": "Skonfiguruj źródło warstwy",
    "setGeocoderURL": "Skonfiguruj adres URL geokodera",
    "searchableLayer": "Warstwa obiektów",
    "name": "Nazwa",
    "countryCode": "Kod(-y) kraju",
    "countryCodeEg": "np. ",
    "countryCodeHint": "Pozostawienie pustego pola spowoduje przeszukiwanie wszystkich krajów",
    "locatorUrl": "Adres URL geokodera",
    "locatorName": "Nazwa geokodera",
    "locatorExample": "Przykład",
    "locatorWarning": "Ta wersja usługi geokodowania nie jest obsługiwana. Widżet obsługuje usługę geokodowania w wersji 00.0 i nowszych.",
    "locatorTips": "Sugestie są niedostępne ponieważ usługa geokodowania nie obsługuje funkcji sugestii.",
    "layerSource": "Źródło warstwy",
    "searchLayerTips": "Sugestie są niedostępne ponieważ usługa obiektowa nie obsługuje funkcji paginacji.",
    "placeholder": "Tekst zastępczy",
    "searchFields": "Pola wyszukiwania",
    "displayField": "Wyświetl pole:",
    "exactMatch": "Dokładne dopasowanie",
    "maxResults": "Wyniki maksymalne",
    "setSearchFields": "Skonfiguruj pola wyszukiwania",
    "set": "Ustaw",
    "fieldSearchable": "możliwe do wyszukiwania",
    "fieldName": "Nazwa",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Anuluj",
    "invalidUrlTip": "Wprowadzony adres URL jest nieprawidłowy lub nieosiągalny."
  })
);