define(
   ({
    "instruction": "Adicionar e configurar serviços de geocodificação ou camadas de elemento como fontes de pesquisa. Estas fontes especificadas determinar o que é pesquisável dentro da caixa de pesquisa.",
    "add": "Adicionar Fonte de Pesquisa",
    "addGeocoder": "Adicionar um Geocoder",
    "geocoder": "Geocodificador",
    "setLayerSource": "Definir Fonte de Camada",
    "setGeocoderURL": "Definir URL Geocodificador",
    "searchableLayer": "Camada de Elementos",
    "name": "Nome",
    "countryCode": "Código(s) País",
    "countryCodeEg": "e.g ",
    "countryCodeHint": "Deixar este valor em branco irá pesquisar todos os países",
    "locatorUrl": "Geocoder URL",
    "locatorName": "Nome do Geocoder",
    "locatorExample": "Exemplo",
    "locatorWarning": "URL Geocodificador O widget suporta serviço de geocodificação 00.0 e superior.",
    "locatorTips": "Sugestões não estão disponíveis porque o serviço de geocodificação não suporta a capacidade sugerida.",
    "layerSource": "Camada Fonte",
    "searchLayerTips": "Sugestões não estão disponíveis porque o serviço de elemento não suporta capacidades de paginação.",
    "placeholder": "Local de introdução de texto",
    "searchFields": "Campos de Pesquisa",
    "displayField": "Exibir Campo",
    "exactMatch": "Correspondência Exacta",
    "maxResults": "Resultados Máximos",
    "setSearchFields": "Definir Campos de Pesquisa",
    "set": "Definir",
    "fieldSearchable": "pesquisável",
    "fieldName": "Nome",
    "fieldAlias": "Nome Alternativo",
    "ok": "OK",
    "cancel": "Cancelar",
    "invalidUrlTip": "O URL que introduziu é inválido ou encontra-se inacessível."
  })
);