define(
   ({
    "instruction": "Προσθέστε και διαμορφώστε geocode service ή feature layer ως πηγές αναζήτησης. Αυτές οι καθορισμένες πηγές προσδιορίζουν τι μπορείτε να αναζητήσετε στο πλαίσιο αναζήτησης.",
    "add": "Προσθήκη πηγής αναζήτησης",
    "addGeocoder": "Προσθήκη Εργαλείου Γεωκωδικοποίησης",
    "geocoder": "Γεωκωδικοποίηση",
    "setLayerSource": "Ορισμός πηγής θεματικού επιπέδου",
    "setGeocoderURL": "Ορισμός URL Εργαλείου γεωκωδικοποίησης",
    "searchableLayer": "Feature Layer",
    "name": "Όνομα",
    "countryCode": "Κωδικός (-οί) χώρας (-ών)",
    "countryCodeEg": "π.χ. ",
    "countryCodeHint": "Εάν αφήσετε κενή αυτήν την τιμή, θα γίνει αναζήτηση σε όλες τις χώρες",
    "locatorUrl": "URL Εργαλείου Γεωκωδικοποίησης",
    "locatorName": "Όνομα Εργαλείου Γεωκωδικοποίησης",
    "locatorExample": "Παράδειγμα",
    "locatorWarning": "Αυτή η έκδοση του geocoding service δεν υποστηρίζεται. Αυτό το widget υποστηρίζει geocoding service 00.0 και άνω.",
    "locatorTips": "Δεν διατίθενται προτάσεις επειδή το geocoding service δεν υποστηρίζει δυνατότητα προτάσεων.",
    "layerSource": "Πηγή θεματικού επιπέδου",
    "searchLayerTips": "Δεν διατίθενται προτάσεις επειδή το feature service δεν υποστηρίζει δυνατότητα σελιδοποίησης.",
    "placeholder": "Κείμενο υπόδειξης",
    "searchFields": "Πεδία αναζήτησης",
    "displayField": "Πεδίο εμφάνισης",
    "exactMatch": "Ακριβής αντιστοιχία",
    "maxResults": "Μέγιστος αριθμός αποτελέσματα",
    "setSearchFields": "Ορισμός πεδίων αναζήτησης",
    "set": "Ορισμός",
    "fieldSearchable": "με δυνατότητα αναζήτησης",
    "fieldName": "Όνομα",
    "fieldAlias": "Ψευδώνυμο",
    "ok": "ΟΚ",
    "cancel": "Ακύρωση",
    "invalidUrlTip": "Το URL που εισαγάγατε δεν είναι έγκυρο ή δεν είναι προσβάσιμο."
  })
);